### ISSUE TITLE
自定义动作视图优先级错误.

### ISSUE THREAD

**Issue by lionof** [mingdaocom/pd#23]
自定义操作需要填写操作原因，比如说作废订单需要填写作废原因，设置的是表内字段；
![image](https://user-images.githubusercontent.com/6542132/97678570-ff13b980-1ace-11eb-8f7b-833691e4ef90.png)
而这个字段又设置了只有订单处于作废状态后才会显示；
![image](https://user-images.githubusercontent.com/6542132/97678609-1357b680-1acf-11eb-9a0e-451a948db8b9.png)
然后执行操作的时候就会发现这个字段直接不显示了，因为在执行流程前状态还不满足显示的条件
![image](https://user-images.githubusercontent.com/6542132/97678642-1eaae200-1acf-11eb-93d9-6a20e174d147.png)
自定义操作中的填写是否额外处理下视图的优先级!

**Comment by lionof** [comment]
> 自定义操作需要填充操作原因，比如说作废订单需要填充作废原因，设置的是表内分区； 而此分区又设置了只有订单处于作废状态后才会显示； 然后执行操作的时候就会发现这个分区直接不显示了，因为在执行流程前状态还不满足显示的条件 自定义操作中的填充是否有多余处理下视图的优先级！
> ![图片](https://user-images.githubusercontent.com/6542132/97678570-ff13b980-1ace-11eb-8f7b-833691e4ef90.png)
> 
> ![图片](https://user-images.githubusercontent.com/6542132/97678609-1357b680-1acf-11eb-9a0e-451a948db8b9.png)
> 
> ![图片](https://user-images.githubusercontent.com/6542132/97678642-1eaae200-1acf-11eb-93d9-6a20e174d147.png)

**Comment by beckjin** [comment]
收到。

**Comment by beckjin** [comment]
我们计划在后面的版本中支持在自定义动作配置时给字段设置默认值，这样就能符合显示规则了。 

目前的解决方案是建议自定义动作改成修改订单状态的方式，选作废，出现作废原因字段，你参考下。
