### ISSUE TITLE
K8S多实例部署后无法激活

### ISSUE THREAD

**Issue by iwtctww** [mingdaocom/pd#30]
2.7.0版
按照教程，快速部署一切正常，改为多实例部署方式时，各种组件都正常启动，但到了激活阶段就会显示服务异常如下
![image](https://user-images.githubusercontent.com/70201369/126948267-9be0a5a3-6561-412e-b881-659307f65c1c.png)
未找到任何其他提示或log。

**Comment by beckjin** [comment]
应该是连接 mongodb 有问题，进入 pod， /data/logs/log.log 看看

**Comment by iwtctww** [comment]
谢谢！
我已经参照mysql的格式添加了mongo的用户名密码作为环境变量，但仍然报错。
log.log的主要错误信息是：
……"org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 13 (Unauthorized): 'command createIndexes requires authentication' on server mongodb:27017. The full response is {\"ok\": 0.0, \"errmsg\": \"command createIndexes requires authentication\", \"code\": 13, \"codeName\": \"Unauthorized\"};……

**Comment by iwtctww** [comment]
> 应该是连接 mongodb 有问题，进入 pod， /data/logs/log.log 看看

谢谢！
我已经参照mysql的格式添加了mongo的用户名密码作为环境变量，但仍然报错。
log.log的主要错误信息是：
……"org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 13 (Unauthorized): 'command createIndexes requires authentication' on server mongodb:27017. The full response is {"ok": 0.0, "errmsg": "command createIndexes requires authentication", "code": 13, "codeName": "Unauthorized"};……

**Comment by beckjin** [comment]
mongodb 的连接字符串格式是：mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
