### ISSUE TITLE
服务器重启后，容器没有自动启动

### ISSUE THREAD

**Issue by chendelin1982** [mingdaocom/pd#33]
Hi,
问题：明道云私有云的服务器重启后，容器没有自动启动    
建议：可否在 docker-compose 编排文件中设置 always 重启策略呢？

**Comment by beckjin** [comment]
https://docs.pd.mingdao.com/faq/deployment.html#%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E5%BC%80%E6%9C%BA%E5%90%AF%E5%8A%A8%EF%BC%88centos%E7%A4%BA%E4%BE%8B%EF%BC%89

请参考这里。
