### ISSUE TITLE
接下来会出windows版docker教程么?

### ISSUE THREAD

**Issue by hhuimie** [mingdaocom/pd#34]
请问接下来会出windows版docker教程么?

**Comment by beckjin** [comment]
Windows 版 Docker 应该和 Linux 类似，可以尝试摸索部署下，注意资源要求。

**Comment by hhuimie** [comment]
> Windows 版 Docker 应该和 Linux 类似，可以尝试摸索部署下，注意资源要求。

安装docker, 拉取镜像, 下载管理器成功, amd64版
![image](https://user-images.githubusercontent.com/4830177/218358003-2d1a38a3-8006-4d89-bc24-b88f32162c00.png)
![image](https://user-images.githubusercontent.com/4830177/218358274-be626e1d-5d0c-41be-b246-e47ea2229234.png)

在`git bash`中运行`bash ./service.sh start`错误
`./service.sh: line 366: ./installer: cannot execute binary file: Exec format error`
![image](https://user-images.githubusercontent.com/4830177/218358313-06f615ed-2222-4ec8-a84b-40ccbd694cef.png)

**Comment by beckjin** [comment]
目前开发都是基于 Linux 环境，Windows 暂未实际测试，应该是存在不兼容。
