### ISSUE TITLE
移动web页面外部用户显示问题

### ISSUE THREAD

**Issue by zwtocn** [mingdaocom/pd#37]
移动web页面外部用户不能显示导航栏，只能显示某一个页面。外部用户pc页面显示正常

**Comment by beckjin** [comment]
截图看下

**Comment by zwtocn** [comment]
> 截图看下
![33B207F53EA53EE5651385677303A48E](https://user-images.githubusercontent.com/14216519/229419337-292284ef-ea68-4bc7-8636-5ffc79b971e2.jpg)
上面 的图为外部用户登录应用的界面，我已经设置导航栏在底部，可以对比下面的一张图片。
![14E922209EF8C91BD56FBA0414587772](https://user-images.githubusercontent.com/14216519/229419462-7222cdcf-d429-4427-b643-c06a03a8dc96.jpg)
上面为内部用户登录应用的界面，底部有导航栏。

**Comment by xiecg** [comment]
这两张图的 url 地址不一样，图1是自定义页面的地址，没有底部导航栏是正确的，图2是app首页的地址，所以有底部导航栏。

检查下跳转的 url 地址，portal/mobile/app/{appId} 是正确的。

如果 url 包含了三个id，portal/mobile/app/{appId}/{groupId}/{id} ，就会跳转到自定义页面了，所以就没有底部导航栏了。

**Comment by zwtocn** [comment]
应用登录进去的URL应该是一致的。就算进入的是默认是自定义页面，也应该有图2的那种底部导航栏，不然用户找不到怎么去其它功能的方法

**Comment by zwtocn** [comment]
> 这两张图的 url 地址不一样，图1是自定义页面的地址，没有底部导航栏是正确的，图2是app首页的地址，所以有底部导航栏。
> 
> 检查下跳转的 url 地址，portal/mobile/app/{appId} 是正确的。
> 
> 如果 url 包含了三个id，portal/mobile/app/{appId}/{groupId}/{id} ，就会跳转到自定义页面了，所以就没有底部导航栏了。

应用登录进去的URL应该是一致的。就算进入的是默认是自定义页面，也应该有图2的那种底部导航栏，不然用户找不到怎么去其它功能的方法

**Comment by zwtocn** [comment]
已在4.0.1修复
